env:
  IMAGE_VERSION: "py3.12-sha-5adb143"
  BUILDKITE_CLEAN_CHECKOUT: true

steps:
  - label: "pre-commit"
    command: ".buildkite/scripts/pre_commit.sh"
    agents:
      queue: "default"

  - wait

  - label: "Trigger Tests"
    plugins:
      - monorepo-diff#v1.4.0:
          diff: "git diff --name-only $BUILDKITE_PULL_REQUEST_BASE_BRANCH...HEAD"
          watch:
            - path: 
                - "fastvideo/v1/models/encoders/**/*"
                - "fastvideo/v1/models/loader/**"
                - "fastvideo/v1/tests/encoders/**"
                - "pyproject.toml"
                - "docker/Dockerfile.python3.12"
              config:
                command: "timeout 15m .buildkite/scripts/pr_test.sh"
                label: "Encoder Tests"
                env:
                  - TEST_TYPE=encoder
                agents:
                  queue: "default"
